{consumer_key: '6ZZhf9Zps7DwkAczbar8Q',
consumer_secret: 'E3YnFOa0y22NYqqJtJmH762dVyPQ1jh1ccWWohxU',
oauth_token: '532653428-wcyFa3eSWocr7eSxWy2YZHLKyB1BSgpNPYyTOi5h',
oauth_token_secret: 'R38N9bez312BBHQxJJ2kXgAXRpmP94j5gxEtcYPC40ZVs'}